title: Yuesesdi Blog
email: contact.yuesesdi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Yuesesdi, a mobile prepaid utility app in the Philippines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yuesesdi
github_username:  yuesesdi

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
